apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: vivekname
spec:
  type: LoadBalancer
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080