apiVersion: v1
kind: Pod
metadata: 
  name: nginxin-pod
  namespace: vivekname
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: vivek
                operator: In
                values: 
                  - name
  containers:
    - name: nginxin-con
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "1m"
          memory: "400M"
        limits:
          cpu: "1m"
          memory: "1Gi"
