apiVersion: v1
kind: Pod
metadata: 
  name: nginxin-pod
  namespace: vivekname
spec:
  containers:
    - name: nginxin-con
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "1m"
          memory: "400M"
        limits:
          cpu: "1m"
          memory: "1Gi"
