apiVersion: apps/v1
kind: Deployment
metadata:
 name: vivekdeployment
 namespace: vivekname
 labels: 
   app: vivekdeployment
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector: 
    matchExpressions:
    - key: vivekdev
      operator: In
      values:
        - deep
  template:
    metadata:
      name: hunterpod
      namespace: vivekname
      labels:
        vivekdev: deep
    spec:
      containers:
      - name: huntercon
        image: nginx:perl
        ports:
        - containerPort: 80