apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  namespace: vivekname
spec: 
  volumes:
  - name: vivek-vol
    persistentVolumeClaim: 
      claimName: c-pvc
  containers:
  - image: nginx
    name: nginx-container
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: vivek-vol
      mountPath: /usr/share/nginx/html