apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistant-pv
  namespace: default
  labels:
   app: vivek-tvs
spec:
  accessModes: 
  - ReadWriteMany
  storageClassName: vivekclass
  azureFile: 
    secretName: azure-vivek
    shareName: vivekshare
  capacity: 
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  
    

