apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: persistant-pvc
  namespace: vivekname
spec:
  storageClassName: vivekclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
   matchLabels:
     app: vivek-tvs
  
  

